#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jul 14 22:26:42 PYT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=10
shaderPack=ComplementaryUnbound_r5.8.1.zip
